services:
  liabilities_db:
    image: postgres:15.1
    container_name: liabilities_db
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - liabilities-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: liabilities
    ports:
      - 5432:5432

  app:
    build:
      context: ./
      dockerfile: ./provision/development/Dockerfile
    restart: always
    env_file: common.env
    volumes:
      - ./:/app/
    networks:
      - liabilities-network
    ports:
      - "8000:8000"
    depends_on:
      - liabilities_db

networks:
  liabilities-network:
    driver: bridge
    name: liabilities-network
